networks:
  chat:
    driver: bridge

services:
  lark-tower-web-front:
    image: lark-tower-web-front:latest
    container_name: lark-tower-web-front
    restart: always
    ports:
      - "11003:3000"
    networks:
      - chat

  lark-tower-admin-front:
    image: lark-tower-admin-front:latest
    container_name: lark-tower-admin-front
    restart: always
    ports:
      - "11004:3000"
    networks:
      - chat
    environment:
      - BASE_PATH=admin-web
