networks:
  chat:
    driver: bridge

services:
  lark-tower-web-front:
    image: tomtang123/lark-tower-web-front:release-v1.0.0
    container_name: lark-tower-web-front
    restart: always
    ports:
      - "11003:3000"
    networks:
      - chat

  lark-tower-admin-front:
    image: tomtang123/lark-tower-admin-front:release-v1.0.0
    container_name: lark-tower-admin-front
    restart: always
    ports:
      - "11004:3000"
    networks:
      - chat
    environment:
      - BASE_PATH=NEXT_PUBLIC_BASE_PATH
